// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyh2yv2490rH31GlWx6rc4ltyn1Cl7k-s',
    appId: '1:41225475621:web:778536a1abaf262dd611cc',
    messagingSenderId: '41225475621',
    projectId: 'insurance-flutter-app',
    authDomain: 'insurance-flutter-app.firebaseapp.com',
    storageBucket: 'insurance-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0vKRbkUn1EyPabxQP8-VHvaNALWxyu0',
    appId: '1:41225475621:android:93c36ce3e7d58073d611cc',
    messagingSenderId: '41225475621',
    projectId: 'insurance-flutter-app',
    storageBucket: 'insurance-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0U_kzTL1JidiYbTjypocRUJ36J9R9TQE',
    appId: '1:41225475621:ios:dc1c14c7723c7a56d611cc',
    messagingSenderId: '41225475621',
    projectId: 'insurance-flutter-app',
    storageBucket: 'insurance-flutter-app.appspot.com',
    iosClientId: '41225475621-n3jv7jve035kkm01936j7h6c4t3js9tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.insuranceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0U_kzTL1JidiYbTjypocRUJ36J9R9TQE',
    appId: '1:41225475621:ios:dc1c14c7723c7a56d611cc',
    messagingSenderId: '41225475621',
    projectId: 'insurance-flutter-app',
    storageBucket: 'insurance-flutter-app.appspot.com',
    iosClientId: '41225475621-n3jv7jve035kkm01936j7h6c4t3js9tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.insuranceApp',
  );
}
